version: '3.8'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    depends_on:
      - sqlite

  sqlite:
    image: alpine
    volumes:
      - ./sqlite-data:/sqlite-data
    command: sh -c "sqlite3 /sqlite-data/db.sqlite"
