version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "123%$#¨%$DFfhgv"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
    driver: local