version: '3.8'
services:
  nodejs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    depends_on:
      - sqlite

  sqlite:
    image: sqlite:latest
    volumes:
      - ./sqlite-data:/sqlite-data
    command: >
      sh -c '
        sqlite3 /sqlite-data/db.sqlite &&
        echo "CREATE TABLE IF NOT EXISTS tabela (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT, idade INTEGER);" | sqlite3 /sqlite-data/db.sqlite &&
        echo "INSERT INTO tabela (nome, idade) VALUES (\"João\", 30), (\"Maria\", 25), (\"Pedro\", 40);" | sqlite3 /sqlite-data/db.sqlite'

volumes:
  sqlite-data:
    driver: local
