version: '3.8'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    depends_on:
      - sqlite

  sqlite:
    image: alpine
    volumes:
      - ./sqlite-data:/sqlite-data
    command: sh -c "touch /sqlite-data/db.sqlite && chmod 777 /sqlite-data/db.sqlite && tail -f /dev/null"
